// Guide copy follows the browser workflows, not the API's resource catalogue.
// An optional image on any step replaces the shared placeholder independently.
export const walkthroughSteps = [
    {
        id: 'welcome',
        group: 'Getting started',
        title: 'Make Planner your own',
        intro: 'Capture ideas, choose meaningful work, and reflect on what changed.',
        instructions: [
            'Use the sidebar to open Dashboard, Goals, Tasks, Habits, Notes, Reviews, or AI assistant. On a small screen, open the navigation menu first.',
            'This guide shows one topic at a time. Use Next and Back, or choose any topic from the menu.',
            'Skip, Close, or Finish stops the automatic introduction for your account. The ? beside Appearance always opens this guide again.',
        ],
    },
    {
        id: 'capture',
        group: 'Getting started',
        title: 'Capture first, add detail later',
        intro: 'Start with what you know. You can enrich the idea as it becomes clearer.',
        instructions: [
            'Use New note for an idea or research, New task for an actionable item, and New goal for a desired outcome.',
            'A new Goal needs a name and an Area. Outcome and completion criteria are optional at creation.',
            'Creation dialogs keep their fields when closed. A successful creation clears that draft; while saving, wait for the result before closing or submitting again.',
        ],
    },
    {
        id: 'today',
        group: 'Dashboard',
        title: 'See what needs attention today',
        intro: 'Open Dashboard and choose Today to focus on current work.',
        instructions: [
            'Review tasks scheduled or due today and tasks already overdue. Open a task to see its details and checklist.',
            'The summary shows selected-task completion, daily activity, and Habit streak. Current focus offers ✎ Edit (one fifth) and ✓ Complete (four fifths); completion follows normal checklist rules.',
            'Refresh reloads the Dashboard. Empty sections link to the relevant feature so you can start adding work.',
        ],
    },
    {
        id: 'week',
        group: 'Dashboard',
        title: 'Choose your work for this week',
        intro: 'This week shows the Tasks and Milestones you deliberately selected.',
        instructions: [
            'On a Task, choose Select for this week. In a Goal’s focused Milestone, choose Select for week.',
            'Return to Dashboard → This week to see those selections together.',
            'Open a Task directly, or open a Milestone in its parent Goal. A weekly selection is a focus choice; it does not mark work complete.',
        ],
    },
    {
        id: 'activity',
        group: 'Dashboard',
        title: 'Read your completion history',
        intro: 'Activity shows a monthly calendar of recorded completions.',
        instructions: [
            'Browse earlier months with the month controls. Hover over a day or focus it with the keyboard to read its date and breakdown.',
            'Colors represent 0, 1, 2–3, 4–6, or 7+ unreversed Task, Checklist, Habit, and Milestone completions.',
            'Creating items and editing Notes do not count. These are factual counts, not a productivity score; the Dashboard shows the timezone used.',
        ],
    },
    {
        id: 'areas',
        group: 'Goals and roadmaps',
        title: 'Give your Goals a home',
        intro: 'Areas organize Goals around meaningful parts of your life.',
        instructions: [
            'Open Goals → Manage areas to rename initial labels or Add area. Areas shows average root Goal progress; Timeline sorts existing deadlines and includes unplanned Goals.',
            'Choose New goal, enter a name, and select its Area. Expand Add details if you already know the desired outcome or completion criteria.',
            'Open a Goal from the list. Expand existing child Goals in the tree when you need their context.',
        ],
    },
    {
        id: 'roadmap',
        group: 'Goals and roadmaps',
        title: 'Explore a Goal’s roadmap',
        intro: 'Roadmap is a fishbone diagram: Milestone branches join a spine leading to the named Goal.',
        instructions: [
            'Choose Add milestone to create a checkpoint with a name and completion criteria.',
            'Each card shows its name, Task counts, progress and state. Select a Milestone to focus on its Tasks; use Back to roadmap to return.',
            'Use Previous/Next milestones for larger roadmaps; each desktop view shows six cards. Select the named Goal head to read its information. Edit goal, Strategy, and Related work open one at a time in that dialog.',
        ],
    },
    {
        id: 'milestone',
        group: 'Goals and roadmaps',
        title: 'Work within a Milestone',
        intro: 'A focused Milestone keeps its criteria, Tasks, and next actions together.',
        instructions: [
            'Choose Add task to create work beneath this Milestone. Open a Task for its checklist and notes, or complete/reopen it from the Task row.',
            'Switch between Tasks and Recurring work. Recurring occurrences are shown separately and excluded from finite Task progress.',
            'Select the Milestone for the week when it needs attention. Each Milestone keeps its own unsaved creation draft while you switch branches.',
        ],
    },
    {
        id: 'completion',
        group: 'Goals and roadmaps',
        title: 'Understand completion and progress',
        intro: 'The app keeps Task, Milestone, and Goal completion distinct.',
        instructions: [
            'An unfinished prerequisite blocks Milestone completion, while its Tasks remain usable. Completing a Milestone with open Tasks requires acknowledgement.',
            'Goal percentages use finite primary children. Habits, contribution links, recurring occurrences, and Strategy notes do not raise that percentage.',
            'Complete a Goal when its finite children are complete. Reopening finite work beneath completed Goals asks you to confirm the affected ancestors; adding finite work requires reopening the Goal first.',
        ],
    },
    {
        id: 'strategy',
        group: 'Goals and roadmaps',
        title: 'Keep your method in Strategy',
        intro: 'Strategy holds principles and learning methods used throughout the Goal.',
        instructions: [
            'Select the Goal head → Strategy to record resources, learning cycles, and your approach, then choose Save strategy.',
            'For example: diagnose a gap → understand the model → build a small project → debug → explain what you learned.',
            'These notes support the entire roadmap and do not affect progress. Refresh preserves unsaved text; read the saved/unsaved indicator before leaving.',
        ],
    },
    {
        id: 'goal-details',
        group: 'Goals and roadmaps',
        title: 'Clarify what success means',
        intro: 'Goal details gives an outcome a clear definition.',
        instructions: [
            'Select the Goal head → Edit goal to change its name, description, desired outcome, and completion criteria.',
            'Set importance from 1 to 5 and an optional deadline when those help you prioritize.',
            'Choose Save goal details. Criteria describe success in your own words; the app does not automatically judge whether that text has been satisfied.',
        ],
    },
    {
        id: 'relationships',
        group: 'Goals and roadmaps',
        title: 'Recognize related work',
        intro: 'A roadmap is one view of a Goal, rather than a required structure for all work.',
        instructions: [
            'Select the Goal head → Related work → Show to select child Goals, direct Tasks, recurring work, Habits, or contributions already associated with this Goal.',
            'Select Direct tasks to add a Task directly beneath the Goal without a Milestone.',
            'A contribution explains support for another Goal; it does not reparent the item or count toward that Goal’s finite progress.',
        ],
    },
    {
        id: 'tasks',
        group: 'Tasks',
        title: 'Capture and find actionable work',
        intro: 'Tasks is your list of work, including items captured without a parent.',
        instructions: [
            'Choose New task and capture an inbox item, or optionally choose a Goal/Milestone in Add to. Suggested text is an editable shortcut, never required.',
            'Today matches due/scheduled tasks in your account timezone. Next matches future dates, This week uses weekly selections, and Backlog shows undated/unselected work. All includes overdue work. Open Filter and search for name/status filters and use pagination.',
            'Open a Task to see its state and definition of done. Its context link returns to its Goal or Milestone; an unassigned Task is labeled Inbox.',
        ],
    },
    {
        id: 'task-edit',
        group: 'Tasks',
        title: 'Clarify and schedule a Task',
        intro: 'Use ✎ Edit task from the detail page or Current focus.',
        instructions: [
            'Edit the name, description, and criteria. Expand Outcome, dates and planning for expected result, importance, estimated minutes, status, start date, deadline, and scheduled start/end in UTC.',
            'Estimated minutes is optional (1–1440), not time tracking. Dates and weekly selections power filters without creating new statuses.',
            'Save task applies versioned changes. A conflict preserves your draft and offers Use saved version or Keep my draft. Completed Tasks use Reopen to change status.',
        ],
    },
    {
        id: 'checklist',
        group: 'Tasks',
        title: 'Use a Checklist to finish the work',
        intro: 'Task → Overview keeps the description, expected result, estimated minutes, and completion criteria beside the Checklist.',
        instructions: [
            'Enter a small step and choose Add. Check or uncheck existing items as you work.',
            'Choose Complete task when the work is done. If Checklist items remain open, explicitly acknowledge them before completing.',
            'Completing the Task does not check its Checklist automatically. Reopen allows you to continue the work and records the reversal of completion.',
        ],
    },
    {
        id: 'task-notes',
        group: 'Tasks',
        title: 'Keep notes beside a Task',
        intro: 'Quick notes in Overview and Task → Notes share the same research, links, and decisions.',
        instructions: [
            'Write in Working notes and choose Save note. This Task editor uses explicit saving.',
            'Switching Overview/Notes or updating the Checklist preserves the draft. Related work lists contributing Goals. Notes → Resources recognizes HTTP links in your draft; Write returns to the editor.',
            'If the note changed elsewhere, choose Use saved version or Keep my draft, then save the chosen draft. A leave warning protects unsaved text; browser-crash recovery is not promised for this editor.',
        ],
    },
    {
        id: 'habits',
        group: 'Habits and recurring Tasks',
        title: 'Record a Habit check-in',
        intro: 'Habits tracks repeated practice without turning it into finite Goal progress.',
        instructions: [
            'Open Habits → Check-ins → New habit. Enter its name, daily/weekly period, and target days.',
            'Choose a dated dot in the recent seven days to check in or undo that day. Each Habit displays its timezone. Streak counts consecutive recorded local dates with at least one check-in, with yesterday grace until today’s check-in.',
            'Weekly check-ins count distinct days toward the weekly target. Check-ins contribute to Activity history, while Habit practice stays outside Goal percentages.',
        ],
    },
    {
        id: 'recurrence',
        group: 'Habits and recurring Tasks',
        title: 'Create work on a repeating schedule',
        intro: 'Recurring Tasks generates separate Task occurrences from a series.',
        instructions: [
            'Choose Recurring tasks → New recurring task. Set a name, start date, daily/weekly frequency, and interval; weekly schedules also select weekdays.',
            'Expand End date and time for optional limits or a local time. Preview the upcoming dates before creating the series.',
            'Occurrences are Tasks you can complete individually. Daily and weekly schedules are supported; the current browser flow does not offer monthly recurrence.',
        ],
    },
    {
        id: 'series-state',
        group: 'Habits and recurring Tasks',
        title: 'Pause, resume, or end a series',
        intro: 'Series state controls future recurring work.',
        instructions: [
            'Pause temporarily stops new occurrences. Resume allows the series to generate them again.',
            'End asks for confirmation before ending the series today and archiving future occurrences that have not started.',
            'Review the displayed series state, frequency, and date range. Completing a single occurrence does not end the series, and recurring work stays outside finite Goal progress.',
        ],
    },
    {
        id: 'notes',
        group: 'Notes',
        title: 'Write and keep ideas',
        intro: 'Notes is the home for freeform ideas, research, and information worth keeping.',
        instructions: [
            'Choose New note, then enter a title and content. Notes saves automatically after edits; wait for Saved to know the server acknowledged the current revision.',
            'Open an existing Note to continue writing. Choose its color and use Pin to make important Notes easier to find.',
            'Delete asks for confirmation. Use it only when you intend to remove the Note and its associated files.',
        ],
    },
    {
        id: 'note-library',
        group: 'Notes',
        title: 'Find and organize Notes',
        intro: 'Search, Tags, and layout controls help you recognize information quickly.',
        instructions: [
            'Search titles and content, filter by Tags, and clear filters to return to All notes. Use the page controls for larger libraries.',
            'Switch Grid/List with the layout buttons. Note colors and pinned markers help distinguish items.',
            'Open Manage tags to create, rename, or delete Tags. In a Note, use Tags to assign up to 20; on mobile, Manage tags remains available in the Notes header.',
        ],
    },
    {
        id: 'attachments',
        group: 'Notes',
        title: 'Attach supporting files',
        intro: 'Keep reference material with the Note it belongs to.',
        instructions: [
            'After the Note has been saved, choose Add files in its Attachments section and select supported files.',
            'Watch upload progress and the displayed error if a file is rejected. Open or download an attachment using its available control.',
            'Remove an attachment when it is no longer needed. Files belong to your authenticated account; AI does not receive Note content or attachments by default.',
        ],
    },
    {
        id: 'note-recovery',
        group: 'Notes',
        title: 'Handle unsaved or conflicting Notes',
        intro: 'Read save state before leaving, especially when the network or session changes.',
        instructions: [
            'Use Retry after a failed autosave. If the session expires, sign in in another window and choose Check again to continue with the draft.',
            'If another window changed the Note, compare Server version and Your draft, then choose Use server version or Keep my draft.',
            'On return, a stored unsaved Note may offer Recover or Discard. Recovery is scoped to this account and browser; never discard unless you intend to lose those edits.',
        ],
    },
    {
        id: 'reviews',
        group: 'Reviews',
        title: 'Create a reflection for a period',
        intro: 'Reviews combines a period’s recorded facts with your own reflection.',
        instructions: [
            'Choose New review, select Daily, Weekly, or Monthly, and pick a date inside that period. Create draft opens the existing review workflow.',
            'Filter the collection by period and use page controls to find a Review. Select it to open its focused editor.',
            'Back to reviews returns to the collection while retaining this page’s drafts. A Review covers a period, rather than being a Task to complete.',
        ],
    },
    {
        id: 'review-facts',
        group: 'Reviews',
        title: 'Understand the Review’s facts',
        intro: 'The facts are a saved snapshot of the selected period.',
        instructions: [
            'Actions counts unreversed Task/Checklist/Habit/Milestone completions; Wins counts Tasks and Milestones. Completion uses finite Tasks due in the period plus weekly-selected Tasks for weekly reviews, at fact capture. Daily bars show activity; arrows navigate existing reviews of the same kind.',
            'The snapshot does not silently change when you complete more work. Choose Refresh facts when you want a new snapshot.',
            'Refreshing facts preserves unsaved reflection text. Missing history is shown as unavailable rather than reconstructed as if it had been recorded.',
        ],
    },
    {
        id: 'reflection',
        group: 'Reviews',
        title: 'Reflect, save, and finalize',
        intro: 'Choose one reflection section at a time so you can focus on the question.',
        instructions: [
            'Write Reflection, What went well, What went wrong, and What to change next. Choose Save reflections to save the edited fields.',
            'Save before choosing Finalize. A finalized Review is read-only; choose Reopen to edit it again.',
            'If the Review changed elsewhere, reconcile the saved version with your draft explicitly. Page drafts survive section switches; leaving with unsaved text asks for confirmation.',
        ],
    },
    {
        id: 'ai-request',
        group: 'AI assistant',
        title: 'Ask AI for a proposal',
        intro: 'AI can help plan, suggest work, review an item, or draft reflections when the server’s provider is available.',
        instructions: [
            'Select a capability: Help me plan, Suggest goals/milestones/tasks, Review a goal/task, Break a goal into a plan, or Draft review reflections.',
            'Select the Areas, Goals, Milestones, Tasks, or Reviews that may be sent as context. Read the selected-context summary and enter your instructions.',
            'Read the provider consent text, then explicitly agree and choose Generate proposal. Notes and files are not sent by default; unavailable AI is reported as an error.',
        ],
    },
    {
        id: 'ai-approval',
        group: 'AI assistant',
        title: 'Review before applying AI work',
        intro: 'A generated proposal is a suggestion until you approve it.',
        instructions: [
            'Read the proposal summary and operation list. Check that the proposed work matches your intent and selected context.',
            'Choose Apply to create the approved work, or Reject to discard the proposal. AI does not silently edit or delete your existing work.',
            'If context changed or the proposal cannot be applied, read the error and generate a fresh proposal with current context.',
        ],
    },
    {
        id: 'profile',
        group: 'Account and appearance',
        title: 'Manage your profile',
        intro: 'Select your name in the sidebar footer to open Profile. Account settings stay available in this context.',
        instructions: [
            'Update your display name and choose Save changes.',
            'Use Choose image to upload a profile picture, or Remove image to return to the default avatar.',
            'Your email and verification state are displayed for context. Email cannot be changed in this release.',
        ],
    },
    {
        id: 'appearance',
        group: 'Account and appearance',
        title: 'Choose a comfortable workspace',
        intro: 'The top-right Appearance icon opens these settings. Account → Appearance is also available while viewing account settings.',
        instructions: [
            'Themes offers Mountain journey, Forest, Ocean, Pisces · Song Ngư, and Starry sky, independently of Light/Dark. All scenery is bundled; there is no theme upload.',
            'Scenery and quote toggles page background, illustrations, and the quote independently. Enter a private quote and Save quote, or Restore preset. Note preferences holds text size, default color, and Grid/List.',
            'Theme and toggle changes save as selected; custom quotes require Save quote. Read save status. A new default Note color does not recolor existing Notes.',
        ],
    },
    {
        id: 'password',
        group: 'Account and appearance',
        title: 'Change your password or sign out',
        intro: 'Account controls are separate from your planning content.',
        instructions: [
            'Open Password, enter your current password, and enter and confirm the new password. Follow the displayed length requirements.',
            'Changing the password invalidates active sessions and returns you to sign-in.',
            'Use Sign out in the sidebar footer when finished. Save current work first and respond to any unsaved-work warning.',
        ],
    },
    {
        id: 'save-state',
        group: 'Using Planner day to day',
        title: 'Recognize what is actually saved',
        intro: 'Visible save indicators and explicit decisions keep changes understandable.',
        instructions: [
            'Notes autosaves. Goal Strategy, Goal details, Task working notes, and Review reflections use their labeled Save buttons.',
            'Wait for the current revision’s acknowledgement. Text entered while a save is pending can still be unsaved after that request returns.',
            'Read errors before retrying. When offered saved-version/draft choices, select deliberately; keeping a draft still needs an explicit save.',
        ],
    },
    {
        id: 'example',
        group: 'Using Planner day to day',
        title: 'Try a small roadmap of your own',
        intro: 'Example: work toward becoming an AI production engineer.',
        instructions: [
            'Create the Goal in an Area, add a Foundations Milestone, and add a Task such as Build a small HTTP API with clear completion criteria.',
            'Write your recurring learning method in Strategy. Use the Task Checklist for concrete steps and Task Notes for discoveries; save those notes explicitly.',
            'Select the Task for this week, record a daily practice as a Habit, and write a weekly Review. Finish closes this guide; reopen ? whenever you need help.',
        ],
    },
];
