<section class="planning-page" data-reviews-page aria-labelledby="reviews-title">
    <header class="workspace-header"><div><h1 id="reviews-title">Reviews</h1><p>Look back with perspective. Move forward with intention.</p></div></header>
    <p class="field-error is-hidden" data-planning-error role="alert"></p>
    <div class="planning-grid">
        <section class="planning-panel"><h2>Your reviews</h2><div data-review-list aria-live="polite"></div></section>
        <section class="planning-panel creation-panel"><h2>Create a review</h2><p class="panel-description">Choose a moment to pause and take stock.</p><form class="stack-form" data-review-create-form><div class="field"><label for="review-kind">Period</label><select id="review-kind" name="kind"><option value="Daily">Daily</option><option value="Weekly">Weekly</option><option value="Monthly">Monthly</option></select></div><div class="field"><label for="review-date">Date within the period</label><input id="review-date" name="date" type="date" required></div><button class="button button-primary" type="submit">Create draft</button></form></section>
    </div>
    <section class="planning-panel is-hidden" data-review-editor><div class="section-heading"><h2 data-review-heading></h2><div><button class="button button-quiet" type="button" data-review-refresh>Refresh facts</button><button class="button button-primary" type="button" data-review-finalize>Finalize</button><button class="button button-quiet is-hidden" type="button" data-review-reopen>Reopen</button></div></div><p data-review-facts></p><form class="stack-form" data-review-edit-form><div class="field"><label>Reflection<textarea name="reflection" maxlength="20000"></textarea></label></div><div class="field"><label>What went well<textarea name="went_well" maxlength="20000"></textarea></label></div><div class="field"><label>What went wrong<textarea name="went_wrong" maxlength="20000"></textarea></label></div><div class="field"><label>What to change next<textarea name="change_next" maxlength="20000"></textarea></label></div><button class="button button-primary" type="submit">Save reflections</button></form></section>
</section>
